FROM tsuzu/github-actions-runner

RUN apt update && apt install -y lsb-release software-properties-common apt-transport-https gnupg-agent && \
   curl -fsSL https://download.docker.com/linux/ubuntu/gpg | apt-key add - && \
   add-apt-repository \
   "deb [arch=amd64] https://download.docker.com/linux/ubuntu \
   $(lsb_release -cs) \
   stable" && \
   apt update && \
   apt install -y --no-install-recommends docker-ce-cli && \
   rm -rf /var/lib/apt/lists/*
